SET QUOTED_IDENTIFIER, ANSI_NULLS ON
GO


CREATE PROCEDURE [dbo].[SP_BatchUpdate]

(@BatchID uniqueidentifier,
@BatchNumber nvarchar(50), 
@CashierID uniqueidentifier, 
@StoreID uniqueidentifier, 
@BatchStatus int, 
@RegisterID uniqueidentifier,
@OpeningDateTime datetime, 
@ClosingDateTime datetime, 
@OpeningAmount money,
@ClosingAmount money,
@OpenHunderdBills Int,
@OpenFiftyBills Int,
@OpenTwentyBills Int, 
@OpenTenBills Int, 
@OpenFiveBills Int,
@OpenSingels Int, 
@OpenQuarter Int,
@OpenDimes Int,
@OpenNickels Int, 
@OpenPennies Int,
@OpenOther decimal, 
@CloseHunderdBills Int,  
@CloseFiftyBills Int,  
@CloseTwentyBills Int,  
@CloseTenBills Int,  
@CloseFiveBills Int,  
@CloseSingels Int,  
@CloseQuarter Int,  
@CloseDimes Int,  
@CloseNickels Int,  
@ClosePennies Int,  
@CloseOther decimal,
@Status smallint,
@DateModified datetime,
@ModifierID uniqueidentifier)

AS

Update dbo.batch
SET
       	BatchNumber=@BatchNumber,
	CashierID=@CashierID,
	StoreID=@StoreID,
	BatchStatus=@BatchStatus,
	RegisterID=@RegisterID,
	OpeningDateTime=@OpeningDateTime,
	ClosingDateTime=@ClosingDateTime,
	OpeningAmount=@OpeningAmount,
	ClosingAmount=@ClosingAmount,
	OpenHunderdBills=@OpenHunderdBills,
	OpenFiftyBills=@OpenFiftyBills,
	OpenTwentyBills=@OpenTwentyBills,  
	OpenTenBills=@OpenTenBills,
	OpenFiveBills=@OpenFiveBills,
	OpenSingels=@OpenSingels,
	OpenQuarter=@OpenQuarter,
	OpenDimes=@OpenDimes,
	OpenNickels=@OpenNickels,
	OpenPennies=@OpenPennies,  
	OpenOther=@OpenOther,
	CloseHunderdBills=@CloseHunderdBills,
	CloseFiftyBills=@CloseFiftyBills,
	CloseTwentyBills=@CloseTwentyBills,
	CloseTenBills=@CloseTenBills,
	CloseFiveBills=@CloseFiveBills,
	CloseSingels=@CloseSingels,
	CloseQuarter=@CloseQuarter,
	CloseDimes=@CloseDimes,
	CloseNickels=@CloseNickels,
	ClosePennies=@ClosePennies,
	CloseOther=@CloseOther,
	Status=@Status,
	DateModified=dbo.GetLocalDATE(),
	UserModified=@ModifierID
WHERE BatchID=@BatchID and (DateModified=@DateModified or @Datemodified is null)
GO