SET QUOTED_IDENTIFIER, ANSI_NULLS ON
GO


create procedure [dbo].[SP_RegisterItemInsert]
(
@ItemID uniqueidentifier,
@Name nvarchar(4000),
@Description nvarchar(4000),
@ModalNumber nvarchar(50),
@Quantization decimal,
@Unit uniqueidentifier,
@ParentID uniqueidentifier,
@MatrixTableNo uniqueidentifier,
@LinkNo uniqueidentifier,
@Matrix1 nvarchar(50),
@Matrix2 nvarchar(50),
@Matrix3 nvarchar(50),
@Matrix4 nvarchar(50),
@Matrix5 nvarchar(50),
@Matrix6 nvarchar(50),
@BarcodeNumber nvarchar(50),
@CaseBarcodeNumber nvarchar(50),
@CaseQty int,
@CaseDescription nvarchar(50),
@BarcodeType int,
@ItemType int,
@ItemPicture image,
@PicturePath nvarchar(4000),
@ItemPicture2 image,
@PicturePath2 nvarchar(4000),
@ItemPicture3 image,
@PicturePath3 nvarchar(4000),
@IsTemplate bit,
@IsSerial bit,
@ManufacturerID uniqueidentifier,
@ManufacturerPartNo nvarchar(50),
@PriceByCase bit,
@CostByCase bit,
@Status smallint,
@ModifierID uniqueidentifier,
@StoreNo uniqueidentifier,
@DepartmentID uniqueidentifier,
@IsDiscount bit,
@IsTaxable bit,
@TaxID uniqueidentifier,
@IsFoodStampable bit,
@IsWIC bit,
@Cost money,
@ListPrice money,
@Price money,
@PriceA money,
@PriceB money,
@PriceC money,
@PriceD money,
@ExtraCharge1 uniqueidentifier,
@ExtraCharge2 uniqueidentifier,
@ExtraCharge3 uniqueidentifier,
@CogsAccount int,
@IncomeAccount int,
@ProfitCalculation int,
@CommissionQty decimal(19, 3),
@CommissionType int,
@MainSupplierID uniqueidentifier,
@OnHand decimal(19, 3),
@OnOrder decimal(19, 3),
@OnTransferOrder decimal(19, 3),
@ReorderPoint decimal,
@RestockLevel decimal,
@BinLocation nvarchar(50),
@OnWorkOrder decimal,
@DaysForReturn int,
@AVGCost money,
@SalePrice money,
@SaleStartDate datetime,
@SaleEndDate datetime,
@SaleMin int,
@SaleMax int,
@MinForSale money,
@SpecialBuy int,
@SpecialPrice money,
@SpecialBuyFromDate datetime,
@SpecialBuyToDate datetime,
@PrefSaleBy int,
@PrefOrderBy int,
@SaleType int,
@MixAndMatchID uniqueidentifier,
@AssignDate bit
)

as

Declare @ItemStoreID uniqueidentifier
set  @ItemStoreID =NEWID()

exec dbo.SP_ItemMainInsert @ItemID ,@Name ,@Description ,@ModalNumber ,@Quantization,@Unit ,
@ParentID ,@MatrixTableNo ,@LinkNo ,@Matrix1 ,@Matrix2 ,@Matrix3 ,@Matrix4 ,@Matrix5 ,@Matrix6 ,
@BarcodeNumber ,@CaseBarcodeNumber ,@CaseQty ,@CaseDescription ,@BarcodeType ,@ItemType ,@ItemPicture ,
@PicturePath ,@ItemPicture2 ,@PicturePath2 ,@ItemPicture3 ,@PicturePath3 ,@IsTemplate ,@IsSerial ,
@ManufacturerID ,@ManufacturerPartNo ,@PriceByCase ,@CostByCase ,@Status ,@ModifierID  

exec dbo.SP_ItemStoreInsert  @ItemStoreID ,@ItemID ,@StoreNo ,@DepartmentID ,@IsDiscount ,@IsTaxable ,@TaxID ,
@IsFoodStampable ,@IsWIC ,@Cost ,@ListPrice ,@Price ,@PriceA ,@PriceB ,@PriceC ,@PriceD ,
@ExtraCharge1 ,@ExtraCharge2 ,@ExtraCharge3 ,@CogsAccount ,@IncomeAccount ,@ProfitCalculation ,
@CommissionQty ,@CommissionType ,@MainSupplierID ,@OnHand ,@OnOrder ,@OnTransferOrder ,
@ReorderPoint ,@RestockLevel ,@BinLocation ,@OnWorkOrder ,@DaysForReturn ,@AVGCost ,@SalePrice ,
@SaleStartDate ,@SaleEndDate ,@SaleMin ,@SaleMax ,@MinForSale ,@SpecialBuy ,@SpecialPrice ,
@SpecialBuyFromDate ,@SpecialBuyToDate ,@Status ,@ModifierID ,@PrefSaleBy ,@PrefOrderBy ,@SaleType ,
@MixAndMatchID ,@AssignDate
GO