SET QUOTED_IDENTIFIER, ANSI_NULLS ON
GO


CREATE procedure [dbo].[SP_GetSubDepartments]
(
	@DepartmentID uniqueidentifier 
)
as
BEGIN
	WITH TREE(MAINID,TEXT,PARENT) AS
(
	 SELECT DEPARTMENTSTOREID,NAME,PARENTDEPARTMENTID FROM DEPARTMENTSTORE 
	 WHERE PARENTDEPARTMENTID=@DepartmentID --PUT PARENT ID HERE
	 UNION ALL
	 SELECT Z.DEPARTMENTSTOREID,Z.NAME,Z.PARENTDEPARTMENTID FROM  DEPARTMENTSTORE Z
	 INNER JOIN TREE ON TREE.MAINID=Z.PARENTDEPARTMENTID
)
SELECT * FROM TREE

END
GO