SET QUOTED_IDENTIFIER, ANSI_NULLS ON
GO


CREATE PROCEDURE [dbo].[SP_RegistersInsert]
(@RegisterID uniqueidentifier,
@CompName nvarchar(50),
@StoreID uniqueidentifier,
@RegisterNo nvarchar(50),
@ReceiptPrinter nvarchar(1000),
@RecieptPrinterType smallint,
@DeliveryLabelPrinter nvarchar(1000),
@ShelfLabelPrinter nvarchar(1000),
@PoleDisplayType int,
@PoleDisplayPort int,
@PDPortBaudRate int,
@ScannerType int,
@ScannerPort int,
@SCBitsPerSec int,
@SCDataBits int,
@SCParity int,
@SCStopBits decimal,
@ScalePort int,
@SLBitsPerSec int,
@SLDataBits int,
@SLParity int,
@SLStopBits decimal,
@PinPadType int,
@PinPadPort int,
@DrawerType int,
@DrawerCom int,
@DelayTicks int,
@ScaleType int,
@CoinDispenser int,
@CoinDispenserPort int,
@DeviceIP nvarchar(200) = NULL,
@USAePayDevice nvarchar = NULL,
@USAePayAPI	bit = 0,
@HideButtons int = 0,
@Status smallint,
@ModifierID uniqueidentifier,
@ReciptType int =0,
@IsTouchScreen int = 0)

as insert into registers
(RegisterID,
RegisterNo,
CompName,
StoreID,
ReceiptPrinter,
RecieptPrinterType,
DeliveryLabelPrinter,
ShelfLabelPrinter,
PoleDisplayType,
PoleDisplayPort,
PDPortBaudRate,
ScannerType,
ScannerPort,
SCBitsPerSec,
SCDataBits,
SCParity,
SCStopBits,
ScalePort,
SLBitsPerSec,
SLDataBits,
SLParity,
SLStopBits,
PinPadType,
PinPadPort,
DrawerType,
DrawerCom,
DelayTicks,
ScaleType,
CoinDispenser,
CoinDispenserPort,
IsTouchScreen,
DeviceIP,
USAePayDevice,
USAePayAPI,
HideButtons,
[Status],
ReciptType,
DateCreated,
UserCreated,
DateModified,
UserModified)

values

(@RegisterID,
@RegisterNo,
@CompName,
@StoreID,
@ReceiptPrinter,
@RecieptPrinterType,
@DeliveryLabelPrinter,
@ShelfLabelPrinter,
@PoleDisplayType,
@PoleDisplayPort,
@PDPortBaudRate,
@ScannerType,
@ScannerPort,
@SCBitsPerSec,
@SCDataBits,
@SCParity,
@SCStopBits,
@ScalePort,
@SLBitsPerSec,
@SLDataBits,
@SLParity,
@SLStopBits,
@PinPadType,
@PinPadPort,
@DrawerType,
@DrawerCom,
@DelayTicks,
@ScaleType,
@CoinDispenser,
@CoinDispenserPort,
@IsTouchScreen,
@DeviceIP,
@USAePayDevice,
@USAePayAPI,
@HideButtons,
isnull(@Status,1),
@ReciptType,
dbo.GetLocalDATE(),
@ModifierID,
dbo.GetLocalDATE(),
@ModifierID)
GO