SET QUOTED_IDENTIFIER, ANSI_NULLS ON
GO


CREATE PROCEDURE [dbo].[SP_PUBLISH_ERROR]
@PARAM_MACHINE as nvarchar(50),
@PARAM_SOURCE as nvarchar(50),
@PARAM_USER as nvarchar(50),
@PARAM_MESSAGE as nvarchar(4000),
@PARAM_EVENTID as bigint,
@PARAM_DATECREATED as datetime

 AS

insert into Errors(MACHINE,USERNAME,SOURCE,MESSAGE,EventId,DateCreated)
values(@PARAM_MACHINE,@PARAM_USER,@PARAM_SOURCE,@PARAM_MESSAGE
,@PARAM_EVENTID,@PARAM_DATECREATED)
GO