CREATE TABLE [dbo].[itemstoreLog] (
  [ItemStoreID] [uniqueidentifier] NOT NULL,
  [ItemNo] [uniqueidentifier] NOT NULL,
  [StoreNo] [uniqueidentifier] NULL,
  [DepartmentID] [uniqueidentifier] NULL,
  [IsDiscount] [bit] NULL,
  [IsTaxable] [bit] NULL,
  [TaxID] [uniqueidentifier] NULL,
  [IsFoodStampable] [bit] NULL,
  [IsWIC] [bit] NULL,
  [Cost] [money] NULL,
  [ListPrice] [money] NULL,
  [Price] [money] NULL,
  [PriceA] [money] NULL,
  [PriceB] [money] NULL,
  [PriceC] [money] NULL,
  [PriceD] [money] NULL,
  [ExtraCharge1] [uniqueidentifier] NULL,
  [ExtraCharge2] [uniqueidentifier] NULL,
  [ExtraCharge3] [uniqueidentifier] NULL,
  [CogsAccount] [int] NULL,
  [IncomeAccount] [int] NULL,
  [ProfitCalculation] [int] NOT NULL,
  [CommissionQty] [decimal](19, 3) NULL,
  [CommissionType] [int] NOT NULL,
  [PrefSaleBy] [int] NULL,
  [PrefOrderBy] [int] NULL,
  [MainSupplierID] [uniqueidentifier] NULL,
  [OnOrder] [decimal](19, 3) NULL,
  [OnTransferOrder] [decimal](19, 3) NULL,
  [OnHand] [decimal](19, 3) NULL,
  [ReorderPoint] [decimal](19, 3) NULL,
  [RestockLevel] [decimal](19, 3) NULL,
  [BinLocation] [nvarchar](50) NULL,
  [OnWorkOrder] [decimal] NULL,
  [DaysForReturn] [int] NULL,
  [AVGCost] [money] NULL,
  [SaleType] [int] NULL,
  [SalePrice] [money] NULL,
  [SaleStartDate] [datetime] NULL,
  [SaleEndDate] [datetime] NULL,
  [SaleMin] [int] NULL,
  [SaleMax] [int] NULL,
  [MinForSale] [money] NULL,
  [SpecialBuy] [int] NULL,
  [SpecialPrice] [money] NULL,
  [SpecialBuyFromDate] [datetime] NULL,
  [SpecialBuyToDate] [datetime] NULL,
  [MixAndMatchID] [uniqueidentifier] NULL,
  [AssignDate] [bit] NULL,
  [Status] [smallint] NULL,
  [MTDQty] [decimal] NULL,
  [MTDDollar] [money] NULL,
  [PTDQty] [decimal] NULL,
  [PTDDollar] [money] NULL,
  [YTDQty] [decimal] NULL,
  [YTDDollar] [money] NULL,
  [MTDReturnQty] [decimal] NULL,
  [PTDReturnQty] [decimal] NULL,
  [YTDReturnQty] [decimal] NULL,
  [DateCreated] [datetime] NULL,
  [UserCreated] [uniqueidentifier] NULL,
  [DateModified] [datetime] NULL,
  [UserModified] [uniqueidentifier] NULL,
  [TDDate] [datetime] NULL,
  [TDReturnDate] [datetime] NULL,
  [NewPrice] [money] NULL,
  [NewPriceDate] [datetime] NULL,
  [SpecialsMemberOnly] [bit] NULL,
  [CasePrice] [money] NULL,
  [CaseSpecial] [money] NULL,
  [PkgPrice] [money] NULL,
  [PkgQty] [int] NULL,
  [IsCaseDiscount] [bit] NULL,
  [IsPkgDiscount] [bit] NULL,
  [Tare] [decimal](19, 2) NULL,
  [RegCost] [money] NULL,
  [LoyaltyGroupID] [uniqueidentifier] NULL,
  [LoyaltyGroupFromDate] [datetime] NULL,
  [LoyaltyGroupToDate] [datetime] NULL,
  [VoidReason] [nvarchar](50) NULL,
  [LastCount] [int] NULL,
  [CountDate] [datetime] NULL,
  [CountOnHand] [decimal] NULL,
  [RegSalePrice] [money] NULL,
  [LastSoldDate] [datetime] NULL,
  [LastReceivedDate] [datetime] NULL,
  [LastReceivedQty] [int] NULL,
  [SpecialCost] [money] NULL,
  [NetCost] [money] NULL,
  [EstimatedCost] [money] NULL,
  [datecreatedlog] [datetime] NULL,
  [step] [int] NULL,
  [MainSupplierIDValue] [uniqueidentifier] NULL
)
GO