CREATE TABLE [dbo].[ItemSupplyLog] (
  [ItemSupplyID] [uniqueidentifier] NOT NULL,
  [ItemStoreNo] [uniqueidentifier] NULL,
  [SupplierNo] [uniqueidentifier] NULL,
  [TotalCost] [money] NULL,
  [GrossCost] [money] NULL,
  [MinimumQty] [int] NULL,
  [QtyPerCase] [int] NULL,
  [IsOrderedOnlyInCase] [bit] NULL,
  [AverageDeliveryDelay] [int] NULL,
  [ItemCode] [nvarchar](50) NULL,
  [IsMainSupplier] [bit] NULL,
  [SortOrder] [smallint] NULL,
  [Status] [smallint] NULL,
  [DateCreated] [datetime] NULL,
  [UserCreated] [uniqueidentifier] NULL,
  [DateModified] [datetime] NULL,
  [UserModified] [uniqueidentifier] NULL,
  [CaseQty] [decimal] NULL,
  [SalePrice] [money] NULL,
  [AssignDate] [bit] NULL,
  [FromDate] [datetime] NULL,
  [ToDate] [datetime] NULL,
  [OnSpecialReq] [bit] NULL,
  [MinQty] [int] NULL,
  [MaxQty] [int] NULL,
  [UOMType] [int] NULL,
  [ColorName] [nvarchar](50) NULL,
  [datecreatedlog] [datetime] NULL,
  [step] [int] NULL
)
GO