CREATE TABLE [dbo].[Store] (
  [StoreID] [uniqueidentifier] NOT NULL,
  [StoreName] [nvarchar](50) NULL,
  [StoreDescription] [nvarchar](4000) NULL,
  [ParentStore] [uniqueidentifier] NULL,
  [DefaultMarkup] [numeric](28, 3) NULL,
  [DefaultMarkupA] [numeric] NULL,
  [DefaultMarkupB] [numeric] NULL,
  [DefaultMarkupC] [numeric] NULL,
  [DefaultMarkupD] [numeric] NULL,
  [RoundUp] [int] NULL,
  [RoundValue] [decimal](18, 3) NULL,
  [DefaultCogsAccount] [int] NULL,
  [DefaultIncomeAccount] [int] NULL,
  [DefaultTaxNo] [uniqueidentifier] NULL,
  [IsDefaultTaxInclude] [bit] NULL,
  [DefaultProfitCalculation] [int] NULL,
  [StoreEmail] [nvarchar](20) NULL,
  [Logo] [image] NULL,
  [Status] [smallint] NULL,
  [DateCreated] [datetime] NULL,
  [UserCreated] [uniqueidentifier] NULL,
  [DateModified] [datetime] NULL,
  [UserModified] [uniqueidentifier] NULL,
  [IsMainStore] [bit] NULL,
  [StoreNumber] [nvarchar](20) NULL,
  [Address] [nvarchar](50) NULL,
  [CityStateZip] [nvarchar](50) NULL,
  [Country] [nchar](10) NULL,
  [Phone1] [nvarchar](50) NULL,
  [Fax] [nvarchar](20) NULL,
  [Phone2] [nvarchar](20) NULL,
  [DistrictID] [uniqueidentifier] NULL,
  [RegionID] [uniqueidentifier] NULL,
  [DateOpened] [datetime] NULL,
  [DateClosed] [datetime] NULL,
  [ShopperTrackIP] [varchar](20) NULL,
  [Tax2] [uniqueidentifier] NULL,
  [Tax3] [uniqueidentifier] NULL,
  [Tax4] [uniqueidentifier] NULL,
  [StoreInt] [int] IDENTITY,
  [CashDiscount] [decimal](18, 4) NULL,
  [LogoPath] [nvarchar](500) NULL,
  CONSTRAINT [PK_Store] PRIMARY KEY CLUSTERED ([StoreID]) WITH (STATISTICS_NORECOMPUTE = ON)
)
GO