CREATE TABLE [dbo].[DeliveryDetails] (
  [DeliveryID] [int] NULL,
  [DeliveryDetailID] [uniqueidentifier] NOT NULL,
  [ShippingAdress] [uniqueidentifier] NULL,
  [Status] [int] NULL,
  [Note] [char](500) NULL,
  [OrderTypeID] [int] NULL,
  [TransactionID] [uniqueidentifier] NULL,
  [CustomerID] [uniqueidentifier] NULL,
  [SentDate] [datetime] NULL,
  [RegID] [uniqueidentifier] NULL,
  [CashierID] [uniqueidentifier] NULL,
  [Shift] [nvarchar](50) NULL,
  [Box] [int] NULL,
  [Cases] [int] NULL,
  [Driver] [uniqueidentifier] NULL,
  [BeDeliverdDate] [datetime] NULL,
  [DeliverdDate] [datetime] NULL,
  [Freezer] [bit] NULL,
  [DateModified] [datetime] NULL,
  [BatchID] [int] NULL,
  [ReturnedDate] [datetime] NULL,
  [ShippedDate] [datetime] NULL,
  [TempAddress] [nvarchar](70) NULL,
  [TempCityStateZip] [nvarchar](50) NULL,
  [TempName] [nvarchar](70) NULL,
  [TotalScan] [int] NULL,
  [Number] [nvarchar](50) NULL,
  [PackedBy] [uniqueidentifier] NULL,
  [PackedDate] [datetime] NULL,
  [SortOrder] [int] NULL,
  [StatusType] [nvarchar](50) NULL,
  [PaidString] [nvarchar](50) NULL,
  CONSTRAINT [PK_DeliveryDetails] PRIMARY KEY CLUSTERED ([DeliveryDetailID]) WITH (STATISTICS_NORECOMPUTE = ON)
)
GO