CREATE TABLE [dbo].[GlobalChangeEntry] (
  [GlobalChangeID] [uniqueidentifier] NOT NULL,
  [ItemStoreID] [uniqueidentifier] NULL,
  [ItemNo] [uniqueidentifier] NOT NULL,
  [StoreNo] [uniqueidentifier] NULL,
  [DepartmentID] [uniqueidentifier] NULL,
  [Cost] [money] NULL,
  [ListPrice] [money] NULL,
  [Price] [money] NULL,
  [PriceA] [money] NULL,
  [PriceB] [money] NULL,
  [PriceC] [money] NULL,
  [PriceD] [money] NULL,
  [ExtraCharge1] [uniqueidentifier] NULL,
  [ExtraCharge2] [uniqueidentifier] NULL,
  [ExtraCharge3] [uniqueidentifier] NULL,
  [MainSupplierID] [uniqueidentifier] NULL,
  [BinLocation] [nvarchar](50) NULL,
  [AVGCost] [money] NULL,
  [SaleType] [int] NULL,
  [SalePrice] [money] NULL,
  [SaleStartDate] [datetime] NULL,
  [SaleEndDate] [datetime] NULL,
  [SaleMin] [int] NULL,
  [SaleMax] [int] NULL,
  [MinForSale] [money] NULL,
  [SpecialBuy] [int] NULL,
  [SpecialPrice] [money] NULL,
  [SpecialBuyFromDate] [datetime] NULL,
  [SpecialBuyToDate] [datetime] NULL,
  [MixAndMatchID] [uniqueidentifier] NULL,
  [AssignDate] [bit] NULL
)
GO