CREATE TABLE [dbo].[SaleTimes] (
  [DateCreated] [datetime] NULL,
  [DateModified] [datetime] NULL,
  [Friday] [bit] NULL,
  [FriFrom] [datetime] NULL,
  [FriTo] [datetime] NULL,
  [Munday] [bit] NULL,
  [MunFrom] [datetime] NULL,
  [MunTo] [datetime] NULL,
  [SaleID] [uniqueidentifier] NULL,
  [SaleTimeID] [uniqueidentifier] NULL,
  [Saterday] [bit] NULL,
  [SatFrom] [datetime] NULL,
  [SatTo] [datetime] NULL,
  [Status] [smallint] NULL,
  [Sunday] [bit] NULL,
  [SunFrom] [datetime] NULL,
  [SunTo] [datetime] NULL,
  [ThuFrom] [datetime] NULL,
  [Thursday] [bit] NULL,
  [ThuTo] [datetime] NULL,
  [TueFrom] [datetime] NULL,
  [Tuesday] [bit] NULL,
  [TueTo] [datetime] NULL,
  [UserCreated] [uniqueidentifier] NULL,
  [UserModified] [uniqueidentifier] NULL,
  [WedFrom] [datetime] NULL,
  [Wednesday] [bit] NULL,
  [WedTo] [datetime] NULL
)
GO