CREATE TABLE [dbo].[Resellers] (
  [ResellerID] [uniqueidentifier] NOT NULL CONSTRAINT [DF_Resellers_ResellerID] DEFAULT (newid()),
  [ResellerLName] [nvarchar](50) NULL,
  [ResellerFName] [nvarchar](50) NULL,
  [CompanyName] [nvarchar](50) NULL,
  [Email] [nvarchar](50) NULL,
  [OnlyText] [bit] NULL,
  [Phone] [nvarchar](50) NULL,
  [Address1] [nvarchar](50) NULL,
  [Address2] [nvarchar](50) NULL,
  [City] [nvarchar](50) NULL,
  [StateID] [nvarchar](50) NULL,
  [ZipCode] [nvarchar](50) NULL,
  [UserName] [nvarchar](50) NULL,
  [Password] [nvarchar](50) NULL,
  [SecurityQ] [nvarchar](50) NULL,
  [SecurityA] [nvarchar](50) NULL,
  [DomainName] [nvarchar](50) NULL,
  [DomainIP] [nvarchar](50) NULL,
  [DesignID] [smallint] NULL,
  [CreditCard4Dig] [nvarchar](50) NULL,
  [CreditCardType] [smallint] NULL,
  [CCExpire] [datetime] NULL,
  [SecurityCode] [nvarchar](50) NULL,
  [BankRoutingNum] [nvarchar](50) NULL,
  [BankAccountNum] [nvarchar](50) NULL,
  [BankAccountFullName] [nvarchar](50) NULL,
  [DriverLicenseStateID] [nvarchar](50) NULL,
  [BillFullName] [nvarchar](50) NULL,
  [BillAddress1] [nvarchar](50) NULL,
  [BillAddress2] [nvarchar](50) NULL,
  [BillState] [nvarchar](50) NULL,
  [BillZip] [nvarchar](50) NULL,
  [BillCountry] [nvarchar](50) NULL,
  [BillPhone] [nvarchar](50) NULL,
  [BillUse] [bit] NULL,
  [CommissionPercents] [decimal](19, 2) NULL,
  [LastRegisteredDate] [datetime] NULL,
  [Status] [smallint] NULL CONSTRAINT [DF_Resellers_Status] DEFAULT (1),
  [DateCreated] [datetime] NULL CONSTRAINT [DF_Resellers_DateCreated] DEFAULT (getdate()),
  [UserCreated] [uniqueidentifier] NULL,
  [DateModified] [datetime] NULL CONSTRAINT [DF_Resellers_DateModified] DEFAULT (getdate()),
  [UserModified] [uniqueidentifier] NULL,
  CONSTRAINT [PK_Resellers] PRIMARY KEY CLUSTERED ([ResellerID]) WITH (STATISTICS_NORECOMPUTE = ON)
)
GO