CREATE TABLE [dbo].[WorkOrder] (
  [WorkOrderID] [uniqueidentifier] NOT NULL,
  [ActiveDate] [datetime] NULL,
  [ExpirationDate] [datetime] NULL,
  [WONo] [nvarchar](50) NULL,
  [StoreID] [uniqueidentifier] NULL,
  [CustomerID] [uniqueidentifier] NULL,
  [Debit] [money] NULL,
  [StartSaleTime] [datetime] NULL,
  [EndSaleTime] [datetime] NULL,
  [Tax] [money] NULL,
  [TaxType] [nvarchar](50) NULL,
  [TaxRate] [decimal](19, 4) NULL,
  [TaxID] [uniqueidentifier] NULL,
  [ShipTo] [uniqueidentifier] NULL,
  [ShipVia] [uniqueidentifier] NULL,
  [Pay_TenderType] [int] NULL,
  [Pay_PaymentType] [smallint] NULL,
  [Pay_CardNumber] [nvarchar](50) NULL,
  [Pay_NameOnCard] [nvarchar](50) NULL,
  [Pay_ExpirationDate] [datetime] NULL,
  [Pay_SecurityCode] [nvarchar](50) NULL,
  [IsWeb] [bit] NULL,
  [WOStatus] [smallint] NULL,
  [Note] [nvarchar](4000) NULL,
  [Freight] [money] NULL,
  [ResellerID] [uniqueidentifier] NULL,
  [Status] [smallint] NULL,
  [DateCreated] [datetime] NULL,
  [UserCreated] [uniqueidentifier] NULL,
  [DateModified] [datetime] NULL,
  [UserModified] [uniqueidentifier] NULL,
  PRIMARY KEY CLUSTERED ([WorkOrderID])
)
GO