CREATE TABLE [dbo].[tranEntryTemp] (
  [AVGCost] [money] NULL,
  [Cost] [money] NULL,
  [DateCreated] [datetime] NULL,
  [DateModified] [datetime] NULL,
  [DepartmentID] [uniqueidentifier] NULL,
  [DiscountAmount] [money] NULL,
  [DiscountOnTotal] [decimal](19, 3) NULL,
  [DiscountPerc] [decimal](19, 3) NULL,
  [ItemStoreID] [uniqueidentifier] NULL,
  [Note] [nvarchar](50) NULL,
  [ParentTransactionEntry] [uniqueidentifier] NULL,
  [PriceExplanation] [nvarchar](50) NULL,
  [Qty] [decimal](19, 3) NULL,
  [RegUnitPrice] [money] NULL,
  [ReturnReason] [int] NULL,
  [SaleCode] [nvarchar](50) NULL,
  [Sort] [int] NULL,
  [Status] [smallint] NULL,
  [Taxable] [bit] NULL,
  [Total] [money] NULL,
  [TransactionEntryID] [uniqueidentifier] NOT NULL,
  [TransactionEntryType] [int] NOT NULL,
  [TransactionID] [int] NULL,
  [UOMPrice] [money] NULL,
  [UOMQty] [decimal](19, 3) NULL,
  [UOMType] [money] NULL,
  [UserCreated] [uniqueidentifier] NULL,
  [UserModified] [uniqueidentifier] NULL
)
GO