CREATE TABLE [dbo].[ITMA] (
  [ItemID] [uniqueidentifier] NOT NULL,
  [Name] [nvarchar](50) NULL,
  [Description] [nvarchar](4000) NULL,
  [ModalNumber] [nvarchar](50) NULL,
  [Quantization] [decimal](28, 3) NULL,
  [Unit] [uniqueidentifier] NULL,
  [ParentID] [uniqueidentifier] NULL,
  [MatrixTableNo] [uniqueidentifier] NULL,
  [LinkNo] [uniqueidentifier] NULL,
  [Matrix1] [nvarchar](50) NULL,
  [Matrix2] [nvarchar](50) NULL,
  [Matrix3] [nvarchar](50) NULL,
  [Matrix4] [nvarchar](50) NULL,
  [Matrix5] [nvarchar](50) NULL,
  [Matrix6] [nvarchar](50) NULL,
  [BarcodeNumber] [nvarchar](50) NULL,
  [CaseBarcodeNumber] [nvarchar](50) NULL,
  [CaseQty] [int] NULL,
  [CaseDescription] [nvarchar](50) NULL,
  [BarcodeType] [int] NULL,
  [ItemType] [int] NULL,
  [ItemPicture] [image] NULL,
  [PicturePath] [nvarchar](4000) NULL,
  [ItemPicture2] [image] NULL,
  [PicturePath2] [nvarchar](4000) NULL,
  [ItemPicture3] [image] NULL,
  [PicturePath3] [nvarchar](4000) NULL,
  [IsTemplate] [bit] NULL,
  [IsSerial] [bit] NULL,
  [ManufacturerID] [uniqueidentifier] NULL,
  [ManufacturerPartNo] [nvarchar](50) NULL,
  [PriceByCase] [bit] NULL,
  [CostByCase] [bit] NULL,
  [Size] [nvarchar](50) NULL,
  [Status] [smallint] NULL,
  [DateCreated] [datetime] NULL,
  [UserCreated] [uniqueidentifier] NULL,
  [DateModified] [datetime] NULL,
  [UserModified] [uniqueidentifier] NULL,
  [ExtraInfo] [nvarchar](500) NULL,
  [Units] [decimal](18, 2) NULL,
  [Meaasure] [int] NULL,
  [CaseBarCode] [nvarchar](25) NULL,
  [ExtraInfo2] [nvarchar](250) NULL,
  [CustomerCode] [nvarchar](50) NULL,
  PRIMARY KEY CLUSTERED ([ItemID]) WITH (STATISTICS_NORECOMPUTE = ON)
)
GO