CREATE TABLE [dbo].[Invoice] (
  [InvoiceID] [uniqueidentifier] NOT NULL,
  [TransactionID] [uniqueidentifier] NULL,
  [CustomeNo] [nvarchar](50) NULL,
  [Name] [nvarchar](50) NULL,
  [Address] [nvarchar](50) NULL,
  [CityStaeZip] [nvarchar](50) NULL,
  [TransactionNo] [nvarchar](50) NULL,
  [TransDate] [datetime] NULL,
  [ShipName] [nvarchar](50) NULL,
  [ShipAdddress] [nvarchar](50) NULL,
  [ShipCityStateZip] [nvarchar](50) NULL,
  [PhoneNo] [nvarchar](50) NULL,
  [Total] [money] NULL,
  [UPC] [nvarchar](50) NULL,
  [ModalNo] [nvarchar](50) NULL,
  [Qty] [numeric](18, 2) NULL,
  [Description] [nvarchar](100) NULL,
  [Price] [money] NULL,
  [ExtPrice] [money] NULL,
  [SortID] [int] NULL,
  [Paid] [money] NULL,
  [Balance] [money] NULL,
  [NewBalance] [money] NULL,
  [Note] [nvarchar](250) NULL,
  [Contact1] [nvarchar](50) NULL,
  [ItemNote] [nvarchar](50) NULL,
  [Tax] [money] NULL,
  [SubTotal] [money] NULL,
  [Cashier] [varchar](50) NULL,
  [Email] [varchar](50) NULL,
  [Tender] [varchar](150) NULL,
  [ShipPhone] [varchar](50) NULL,
  PRIMARY KEY CLUSTERED ([InvoiceID]) WITH (STATISTICS_NORECOMPUTE = ON)
)
GO