CREATE TABLE [dbo].[TransactionBatch] (
  [BatchID] [uniqueidentifier] NOT NULL,
  [BatchNo] [nvarchar](50) NULL,
  [RegisterID] [uniqueidentifier] NULL,
  [UserID] [uniqueidentifier] NULL,
  [StoreID] [uniqueidentifier] NULL,
  [StartTime] [datetime] NULL,
  [CloseTime] [datetime] NULL,
  [OpenAmount] [money] NULL,
  [ActualCash] [money] NULL,
  [Gifts] [money] NULL,
  [AccountReceivable] [money] NULL,
  [TotalPayOut] [money] NULL,
  [LeaveAmount] [money] NULL,
  [Hundred] [int] NULL,
  [Fifty] [int] NULL,
  [Twenty] [int] NULL,
  [Ten] [int] NULL,
  [Five] [int] NULL,
  [Single] [int] NULL,
  [Half] [int] NULL,
  [Quarter] [int] NULL,
  [Dime] [int] NULL,
  [Nickel] [int] NULL,
  [Penny] [int] NULL,
  [Status] [smallint] NULL,
  [DateCreated] [datetime] NULL,
  [UserCreated] [uniqueidentifier] NULL,
  [DateModified] [datetime] NULL,
  [UserModified] [uniqueidentifier] NULL,
  PRIMARY KEY CLUSTERED ([BatchID]) WITH (STATISTICS_NORECOMPUTE = ON)
)
GO