CREATE TABLE [dbo].[PPCPrint] (
  [PrintType] [int] NULL,
  [IsSystem] [bit] NULL,
  [RowsNumberInPage] [int] NULL,
  [LetterSize] [decimal](19, 3) NULL,
  [LeftMargin] [decimal](19, 3) NULL,
  [RightMargin] [decimal](19, 3) NULL,
  [TopMargin] [decimal](19, 3) NULL,
  [BottomMargin] [decimal](19, 3) NULL,
  [PageBreak] [bit] NULL,
  [HeightLine] [decimal](19, 3) NULL,
  [PrintLogo] [bit] NULL,
  [Logo] [image] NULL,
  [LogoX] [decimal](19, 3) NULL,
  [LogoY] [decimal](19, 3) NULL,
  [LogoSizeHeight] [decimal](19, 3) NULL,
  [LogoSizeWidth] [decimal](19, 3) NULL,
  [StoreNameFontSize] [decimal](19, 3) NULL,
  [StoreNameX] [decimal](19, 3) NULL,
  [StoreNameY] [decimal](19, 3) NULL,
  [PropertiesAddressFontSize] [decimal](19, 3) NULL,
  [PropertiesAddressX] [decimal](19, 3) NULL,
  [ItemsTableY] [decimal](19, 3) NULL,
  [QtyCaption] [nvarchar](50) NULL,
  [QtyX] [decimal](19, 3) NULL,
  [QtyLettersNumber] [int] NULL,
  [ItemCodeCaption] [nvarchar](50) NULL,
  [ItemCodeX] [decimal](19, 3) NULL,
  [ItemCodeLettersNumber] [int] NULL,
  [ItemNameCaption] [nvarchar](50) NULL,
  [ItemNameX] [decimal](19, 3) NULL,
  [ItemNameLettersNumber] [int] NULL,
  [PicesOrCasesCaption] [nvarchar](50) NULL,
  [PicesOrCasesX] [decimal](19, 3) NULL,
  [PicesOrCasesLettersNumber] [int] NULL,
  [PriceCaption] [nvarchar](50) NULL,
  [PriceX] [decimal](19, 3) NULL,
  [PriceLettersNumber] [int] NULL,
  [TotalCaption] [nvarchar](50) NULL,
  [TotalX] [decimal](19, 3) NULL,
  [TotalLettersNumber] [int] NULL,
  [Line1V] [decimal](19, 3) NULL,
  [Line2V] [decimal](19, 3) NULL,
  [Line3V] [decimal](19, 3) NULL,
  [Line4V] [decimal](19, 3) NULL,
  [Line5V] [decimal](19, 3) NULL,
  [Line6V] [decimal](19, 3) NULL,
  [Line7V] [decimal](19, 3) NULL,
  [LinesHorizontalStart] [decimal](19, 3) NULL,
  [LinesHorizontalEnd] [decimal](19, 3) NULL,
  [Line1H] [decimal](19, 3) NULL,
  [Line2H] [decimal](19, 3) NULL,
  [TotalsX] [decimal](19, 3) NULL,
  [PaymentLine1V] [decimal](19, 3) NULL,
  [PaymentLine2V] [decimal](19, 3) NULL,
  [PaymentLine3V] [decimal](19, 3) NULL,
  [PaymentLine4V] [decimal](19, 3) NULL,
  [PaymentLine5V] [decimal](19, 3) NULL,
  [PaymentLine6V] [decimal](19, 3) NULL,
  [PaymentLinesHorizontalStart] [decimal](19, 3) NULL,
  [PaymentLinesHorizontalEnd] [decimal](19, 3) NULL,
  [PaymentLine1H] [decimal](19, 3) NULL,
  [PaymentLine2H] [decimal](19, 3) NULL,
  [DateCaption] [nvarchar](50) NULL,
  [DateX] [decimal](19, 3) NULL,
  [DateLettersNumber] [int] NULL,
  [NoCaption] [nvarchar](50) NULL,
  [NoX] [decimal](19, 3) NULL,
  [NoLettersNumber] [int] NULL,
  [DebitCaption] [nvarchar](50) NULL,
  [DebitX] [decimal](19, 3) NULL,
  [DebitLettersNumber] [int] NULL,
  [ApplyAmountCaption] [nvarchar](50) NULL,
  [ApplyAmountX] [decimal](19, 3) NULL,
  [ApplyAmountLettersNumber] [int] NULL,
  [BalanceCaption] [nvarchar](50) NULL,
  [BalanceX] [decimal](19, 3) NULL,
  [BalanceLettersNumber] [int] NULL,
  [PrintSignature] [bit] NULL,
  [SignatureX] [decimal](19, 3) NULL,
  [SignatureY] [decimal](19, 3) NULL,
  [SignatureHeight] [decimal](19, 3) NULL,
  [SignatureWidth] [decimal](19, 3) NULL,
  [Status] [smallint] NULL,
  [DateCreated] [datetime] NULL,
  [UserCreated] [uniqueidentifier] NULL,
  [DateModified] [datetime] NULL,
  [UserModified] [uniqueidentifier] NULL
)
GO