CREATE TABLE [dbo].[emp] (
  [EMPNO] [int] IDENTITY,
  [ENAME] [varchar](10) NULL CONSTRAINT [DF__emp__ENAME__45832891] DEFAULT (NULL),
  [JOB] [varchar](9) NULL CONSTRAINT [DF__emp__JOB__46774CCA] DEFAULT (NULL),
  [MGR] [int] NULL CONSTRAINT [DF__emp__MGR__476B7103] DEFAULT (NULL),
  [HIREDATE] [datetime] NULL CONSTRAINT [DF__emp__HIREDATE__485F953C] DEFAULT (NULL),
  [SAL] [float] NULL CONSTRAINT [DF__emp__SAL__4953B975] DEFAULT (NULL),
  [COMM] [float] NULL CONSTRAINT [DF__emp__COMM__4A47DDAE] DEFAULT (NULL),
  [DEPTNO] [int] NULL CONSTRAINT [DF__emp__DEPTNO__4B3C01E7] DEFAULT (NULL)
)
GO